apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-upstream
  name: ingress-upstream
  namespace: default
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: match-article-v3
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: match-article-v3
spec:
  selector:
    matchLabels:
      app: match-article-v3
  replicas: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: match-article-v3
    spec:
      containers:
        - name: match-article-v3
          image: jumamiller/article-match-v3
          imagePullPolicy: Always
          resources:
            requests:
              memory: ".5Gi"
              cpu: "500m"
            limits:
              memory: ".5Gi"
              cpu: "500m"
          ports:
            - containerPort: 80