apiVersion: v1
kind: Service
metadata:
  labels:
    app: ingress-upstream
  name: ingress-upstream
  namespace: default
spec:
  ports:
    - name: 80-8080
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: reservation
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reservation
spec:
  selector:
    matchLabels:
      app: reservation
  replicas: 5
  revisionHistoryLimit: 5
  template:
    metadata:
      labels:
        app: reservation
    spec:
      containers:
        - name: reservation
          image: jumamiller/article-match-v1
          imagePullPolicy: Always
          resources:
            requests:
              memory: ".5Gi"
              cpu: "500m"
            limits:
              memory: ".5Gi"
              cpu: "500m"
          ports:
            - containerPort: 80